steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sonicpress:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sonicpress:$COMMIT_SHA']

  # Access secrets and store them in environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Access secrets
        export GCS_BUCKET_NAME=$(gcloud secrets versions access latest --secret=sonicpress-gcs-bucket)
        export LITELLM_PROXY_URL=$(gcloud secrets versions access latest --secret=sonicpress-litellm-proxy-url)
        
        # Create GCS bucket if it doesn't exist
        if ! gsutil ls -b gs://$GCS_BUCKET_NAME &>/dev/null; then
          echo "Creating GCS bucket $GCS_BUCKET_NAME..."
          gsutil mb -l us-central1 gs://$GCS_BUCKET_NAME
          gsutil iam ch allUsers:objectViewer gs://$GCS_BUCKET_NAME
        else
          echo "GCS bucket $GCS_BUCKET_NAME already exists."
        fi
        
        # Deploy to Cloud Run
        gcloud run deploy sonicpress \
          --image=gcr.io/$PROJECT_ID/sonicpress:$COMMIT_SHA \
          --platform=managed \
          --region=us-central1 \
          --memory=2Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --timeout=3600 \
          --set-secrets="MISTRAL_API_KEY=sonicpress-mistral-key:latest,EXA_API_KEY=sonicpress-exa-key:latest,ELEVENLABS_API_KEY=sonicpress-elevenlabs-key:latest" \
          --set-env-vars="LITELLM_PROXY_URL=$LITELLM_PROXY_URL,GCS_BUCKET_NAME=$GCS_BUCKET_NAME" \
          --allow-unauthenticated

# Only store logs, not the artifacts
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/sonicpress:$COMMIT_SHA' 